### ISSUE TITLE
AttributeError with Django 1.10+

### ISSUE THREAD

**Issue by rezemika** [vinyll/django-imagefit#20]
The middleware management changed after Django 1.10, the `MIDDLEWARE_CLASSES` variable became `MIDDLEWARE`. An AttributeError is raised when trying to run a Django project using the `MIDDLEWARE` variable.

```
File ".../venv/lib/python3.5/site-packages/imagefit/conf.py", line 38, in ImagefitConf
    if not 'django.middleware.http.ConditionalGetMiddleware' in settings.MIDDLEWARE_CLASSES:
File ".../venv/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'MIDDLEWARE_CLASSES'
```

**Comment by vinyll** [comment]
Hey @rezemika, thanks for the report.
Would you feel like making a PR with that?
You could upgrade [the version](https://github.com/vinyll/django-imagefit/blob/master/setup.py#L8) and the readme accordingly.
Let me know if you can/can't and ping me for review so I'll be responding faster ;)

**Comment by rezemika** [comment]
@vinyll: It's okay, PR made. :)

**Comment by vinyll** [comment]
It's not appearing on https://github.com/vinyll/django-imagefit/pulls @rezemika. Where did you publish it?

**Comment by rezemika** [comment]
Ah, you're so fast. :)

I'm a few minutes late, sorry.

**Comment by anuj9196** [comment]
I'm having the same issue after installing as given in readme file

**Comment by rezemika** [comment]
@anuj9196 : When I check on https://pypi.org/project/django-imagefit/, it seems like the package was not updated on PyPi, it is still at the version 0.5. So, you should clone the repo and do `python3 setup.py install` to install the latest version of the module in your virtualenv.

**Comment by vinyll** [comment]
Sorry guys, I haden't updated pypi!
Shall do and update here ;)

**Comment by vinyll** [comment]
@rezemika @anuj9196 The package has now been updated on pypi.
You should be able to run `pip install django-imagefilt` to install the latest _0.6_

**Comment by anuj9196** [comment]
I updated to latest version via `pipenv` by uninstall previous version and installing again which installed `0.6`

But now, it has started giving error as

```
File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/imagefit/models.py", line 2, in <module>
    from imagefit.conf import ext_to_format, settings
  File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/imagefit/conf.py", line 8, in <module>
    class ImagefitConf(AppConf):
  File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/imagefit/conf.py", line 43, in ImagefitConf
    setattr(settings, property_name, middlewares + ('django.middleware.http.ConditionalGetMiddleware',))
NameError: name 'middlewares' is not defined
```

**Comment by rezemika** [comment]
Oh no, there's a typo [here](https://github.com/vinyll/django-imagefit/blob/master/imagefit/conf.py#L41). I wonder how it happened, it seems to me that all the tests passed. :/

**Comment by anuj9196** [comment]
So, will you draft a new release or update the same? I need to use it in my application.

**Comment by vinyll** [comment]
Right ~_middleswares_~ > _middlewares_ I suppose that you meant.
That's fixed and uploaded.
Pypi was updated too with version _0.6.1_

Seems like we're missing tests. Any PR will be welcome ;)

**Comment by rezemika** [comment]
I meant "tests I did myself", but I agree. Unfortunately, I won't have many time this week, but don't hesitate to ping me from friday/saturday. ;)

**Comment by anuj9196** [comment]
Thank you for the quick update. But this has lead to a new issue
```
File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/imagefit/models.py", line 2, in <module>
    from imagefit.conf import ext_to_format, settings
  File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/imagefit/conf.py", line 8, in <module>
    class ImagefitConf(AppConf):
  File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/imagefit/conf.py", line 43, in ImagefitConf
    setattr(settings, property_name, middlewares + ('django.middleware.http.ConditionalGetMiddleware',))
TypeError: can only concatenate list (not "tuple") to list
```

**Comment by vinyll** [comment]
@anuj9196: as you have a context under your hands, could you get this working and make a PR?
It should be pretty straightforward.
We currently have this:
```python
['a'] + ('b',)
*** TypeError: can only concatenate list (not "tuple") to list
```

and we want:
```python
('a',) + ('b',)
('a', 'b')
```

You may want to try:
```python
setattr(settings, property_name, tuple(middlewares) + ('django.middleware.http.ConditionalGetMiddleware',))
```

Can you please test and PR (and increase the setup.py version to 0.6.2 ;) )

👍

**Comment by anuj9196** [comment]
PR #24  created
