### ISSUE TITLE
pip install failing

### ISSUE THREAD

**Issue by cjshaw1976** [vinyll/django-imagefit#23]
Good day, I have tried to install using 

> pip install django-imagefit

Getting the following error:

> pip install django-imagefit
> Collecting django-imagefit
>   Using cached django-imagefit-0.6.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-gov7zs6k/django-imagefit/setup.py", line 10, in <module>
>         long_description=open('README.md').read(),
>       File "/home/dbworksc/virtualenv/zimphoto__html/3.5/lib64/python3.5/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 418: ordinal not in range(128)
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gov7zs6k/django-imagefit/
>

**Comment by vinyll** [comment]
I would guess it's trying to read the _README_ file in ascii instead of UTF-8.
Which seems surprising as you're on a Linux system (which in my mind is UTF-8 by default).

Any more hint about this? Anyone experiments the same difficulties?

**Comment by vinyll** [comment]
I've been able to reproduce on a Linux (Ubuntu) with Python 3.4.
Works fine with Python 2.7 and Python 3.6. (Don't know with 3.5).

Can you confirm @cjshaw1976 what version you are using? (and eventually how you built your venv)

**Comment by cjshaw1976** [comment]
Good Day,

I am using Python version 3.5. I do not know what flavour or version of Linux it is using, as it is a shared server.

**Comment by vinyll** [comment]
These versions of Python are now obsolete. Won't fix
