### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by nicobaguio** [vinyll/django-imagefit#25]
Tried using this app to resize one image in my static files. The image didn't render. 

Configurations:
Django: 2.0.3
Python 3.6.4

in settings.py
`IMAGEFIT_ROOT = "myproject"`
`IMAGEFIT_CACHE_ENABLED = False`

The html page where I tried using Imagfit
`{% load static %}`
`{% load imagefit %}`
`{% with 'image/person_pic/'|add:person.pic as person_image %}`
`<img src="{% static person_image|resize:'thumbnail' %}">`

When I checked, the image source comes out to:
/static/%255Eimagefit/resize/thumbnail/image/person_pic/{insert person_id}.png

when I removed the "resize:'thumbnail', the image renders properly.

**Comment by vinyll** [comment]
Are you sure about `<img src="{% static person_image|resize:'thumbnail' %}">` vs `<img src="{{ static person_image|resize:'thumbnail' }}">`?

**Comment by vinyll** [comment]
@nicobaguio Any update about previews comment?

**Comment by nicobaguio** [comment]
@vinyll I've skipped to using CSS max-width + max-height :) I'll try again later.

**Comment by vinyll** [comment]
Right, not serving the same purpose.
Next time you give it a shot try as [the readme is suggesting](https://github.com/vinyll/django-imagefit#templatetags) and feel free to reopen if you have further difficulties and some output for debugging ;)
