### ISSUE TITLE
Not working on Nginx server

### ISSUE THREAD

**Issue by reznov11** [vinyll/django-imagefit#33]
Every time I open website, it gives me an error in console says:

` (index):1 503 (Service Temporarily Unavailable) `

The image is still there but it didn't open

**Comment by vinyll** [comment]
I hardly see the impact it could have on Nginx.
It's been used on Nginx so far without such issues.

@reznov11, can you output the console network call that raises the 503?

**Comment by reznov11** [comment]
The issue is that the module doesn't work with JFIF images format, and that's why it took me long time to figure out what was going on!! now I prevented the users from uploading this kind of format. What seems to be wrong with Nginx, I've just changed Gunicorn to UWSGI with some additional configurations and it works like charm without any 50x errors, don't know what was wrong with it!

**Comment by vinyll** [comment]
I'm still a little surprised that JFIF would not work normally.
Django-imagefit uses PIL that is supposed to [support JFIF image format](https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html#jpeg).

I'll close this for now as we're missing log information to investigate further.
However feel free to reopen if you have more info to investigate and if it confirms that django-imagefit itself is in cause.
