### ISSUE TITLE
Warning logs

### ISSUE THREAD

**Issue by bencipher** [vinyll/django-imagefit#40]
I really don't know why this warning is being logged, can you please explain what the issue is and maybe we can write a test for it?

Here are my usages:
article.feature_img.url|resize:'320x240,C'
article.feature_img.url |resize:'800x420,C'
post.feature_img.url|resize:'thumbnail'

Also, I discover that without the Crop flag, the size is not enforced but when i add the Crop tag, the image fades.

```
imagefit\views.py", line 61, in resize
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured:  "385770" is neither a "WIDTHxHEIGHT" format nor a key in IMAGEFIT_PRESETS.
Internal Server Error: /imagefit/resize/385770//media/feature_default.jpg
```

**Comment by vinyll** [comment]
Hey @bencipher,

I guess you should isolate the line that makes the error out of the current page in order to check where the `385770` comes out from

**Comment by bencipher** [comment]
Okay will try that.

**Comment by bencipher** [comment]
I have seen where the number came from, it's from one of my templates, I will close the issue now.
