### ISSUE TITLE
Latest version not compatible with Django 4

### ISSUE THREAD

**Issue by Aweponken** [vinyll/django-imagefit#41]
The README states that the package is compatible with Django 4, yet the latest release of the package use `django.conf.urls.url()` which was deprecated in Django 3.0, and is removed in Django 4.0+. Is the project still maintained? No new releases to pip since 2018.

```
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.9/site-packages/django/conf/urls/__init__.py)
```

**Comment by vinyll** [comment]
Hey @Aweponken!

Fixing this seems to be pretty straightforward: https://stackoverflow.com/a/70319607/328117
Would you feel like suggesting a PR that we would check together?

**Comment by bencipher** [comment]
Hi @Aweponken, this bug has been fixed but maybe the latest update is not the one installed on PyPi, install it using the repo.

**Comment by bencipher** [comment]
You’re welcome @vinyll should do that or maybe he his planning major updates.

**Comment by vinyll** [comment]
I was hoping to include #38 along with the next release.
The original author has not followed up so we may release a new version for Django 4 without that feature.

**Comment by vinyll** [comment]
Cool @bencipher, your PR was merged.
[Release 0.7.0 was published](https://pypi.org/project/django-imagefit/) 🚀 

This issue is closed for now, however if you meet any issue we'll re-open and release a new minor/bugfix version.
