### ISSUE TITLE
Update for django 4.2

### ISSUE THREAD

**Issue by danielmoessner** [vinyll/django-imagefit#46]
I'm using this library in one of my projects and would like to use it with django 4.2.

2 Things is noticed need to be updated:
In conf.py add this line:
if not settings.configured:
    settings.configure()

In models.py change the line (54):
from ANTIALIAS to PilImage.LANCZOS)
 
I would be really happy if you could change that and push it to pypi as an upgrade.

**Comment by vinyll** [comment]
Hey @danielmoessner 

It seems like you identified the issue and the solutions.
Would you feel like suggesting a PR so we would then merge and publish?

**Comment by Nebuchadrezzar** [comment]
I tried out @danielmoessner changes, and they seem to resolve #44.  I noticed one extra hiccup in the documentation, which provides an example using `url()`.   django.conf.urls.url() was deprecated in Django 3.0, and is removed in Django 4.0+.  So it should probably read:  `re_path(r'^imagefit/', include('imagefit.urls'))`.

**Comment by vinyll** [comment]
Can you post these suggestions in a PR so that we merge it @Nebuchadrezzar?

**Comment by vinyll** [comment]
Fixed in #47 by @Nebuchadrezzar considering @danielmoessner's recommendation 🚀
