### ISSUE TITLE
Need to use io.BytesIO instead of io.StringIO in models.py

### ISSUE THREAD

**Issue by gammadistribution** [vinyll/django-imagefit#9]
Currently using Python 3.2, Pillow 2.4.0, Django 1.6, and bleeding edge version of django-imagefit.

Calling media_resize in template on image produces following error:

Exception Type: AttributeError
Exception Value: type object '_io.StringIO' has no attribute 'StringIO'
Exception Location: /home/matthew/Environments/django1.6_dev/src/django-imagefit/imagefit/models.py in render, line 75

Upon inspection, io.StringIO does indeed not have any attribute StringIO in Python 3.x.  I renamed this to StringIO() as indicated in the docs and received the following error:

Exception Type: TypeError
Exception Value: string argument expected, got 'bytes'
Exception Location: /home/matthew/Environments/django1.6_dev/lib/python3.2/site-packages/PIL/PngImagePlugin.py in _save, line 546

Switching StringIO out for BytesIO in def render() in models.py fixed the problem and rendered the image through the resizing filter in the template.  

There are no tests for me to use to verify this is the correct solution.  Do you think you could test this fix for use in Python 3.2 or greater?

**Comment by Kasperfred** [comment]
I had the same problem, and came the to the same conclusion as you. 

It seems to be working for Python 3.5 as well.

**Comment by vinyll** [comment]
[@Kasperfred's PR](https://github.com/vinyll/django-imagefit/pull/15) is related to this. WIP?

**Comment by gammadistribution** [comment]
I only saw the issue in render(). My solution worked for my purposes, but you should make that fix and test against Python 3.

**Comment by vinyll** [comment]
Should be fixed with latest release (0.5).
Please reopen if it's not the case.
